name: inventory-management-system

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ims:latest
          platforms: linux/amd64
          build-args: |
            ASPNETCORE_ENVIRONMENT=Production
            DEFAULT_CONNECTION=${{ secrets.DEFAULT_CONNECTION }}
            AUTHENTICATION__DEFAULTSCHEME=${{ vars.AUTHENTICATION__DEFAULTSCHEME }}
            AUTHENTICATION__SCHEMES__BEARER__ISSUERSIGNINGKEY=${{ vars.AUTHENTICATION__SCHEMES__BEARER__ISSUERSIGNINGKEY }}
            AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCE=${{ vars.AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCE }}
            AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCES__0=${{ vars.AUTHENTICATION__SCHEMES__BEARER__VALIDAUDIENCES__0 }}
            AUTHENTICATION__SCHEMES__BEARER__VALIDISSUER=${{ vars.AUTHENTICATION__SCHEMES__BEARER__VALIDISSUER }}
